#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456

# https://baomidou.com/pages/a61e1b/#%E6%96%87%E6%A1%A3-documentation

# 关于驱动
# useSSL=false
# characterEncoding=utf-8
# serverTimezone=GMT%2B8
# serverTimezone
# https://dev.mysql.com/doc/connectors/en/connector-j-time-instants.html
# connectionTimeZone
# https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
# java.time.ZoneId
# https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZoneId.html
# UTC vs GMT
# https://www.zhihu.com/question/27052407
# GMT == UTC+0
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组，默认值即为master
      primary: mp
      # 严格匹配数据源，默认false。true: 未匹配到指定数据源时抛异常，false:未匹配到指定数据源时使用默认数据源
      strict: false
      datasource:
        mp:
          #url: jdbc:mysql://39.104.173.57:3306/mp?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        sakila:
          #url: jdbc:mysql://39.104.173.57:3306/sakila?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          url: jdbc:mysql://localhost:3306/sakila?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        test:
          #url: jdbc:mysql://39.104.173.57:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456

# 查看MyBatis-Plus生成的SQL
# 1. @MapperScan -> *Mapper.java
# 2. mybatis-plus.mapper-locations -> *.xml 或者将*.xml放入默认路径，比如resources/mapper/
mybatis-plus:
  configuration:
    # 显示SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰和下划线映射
    #map-underscore-to-camel-case: true
  #global-config:
  #  db-config:
       # 配置统一前缀
  #    table-prefix: t_
       # 全局id默认生成策略
  #    id-type: assign_id
  # 配置默认包前缀
  #type-aliases-package:
  # 配置通用枚举包扫描 + @EnumValue 问题（liuyang）: 如果在多个包下配置了enum该怎么办？202204071319
  #type-enums-package:
  # xml 202204081610 有问题！
  #mapper-locations:
  #  - classpath:/mapper/*.xml
  #  - classpath:/liuyang/testdatambp/modules/user/generated/mapper/mapping/UserMapper.xml
  mapper-locations:
    # 1. 默认扫描位置（如果指定了mapper-locations，则框架不再扫描默认位置，如果需要，比如还是有配置文件放入了resources/mapper/，则必须明确配置！）
    #- classpath*:/mapper/**/*.xml
    # 2. 定制位置 - 配置方法1。注意要配合pom.xml中build里面的配置，否则会报.xml找不到，并且添加配置后要从新刷新maven配置，在进行单测或其他动作。
    #- classpath:/liuyang/testdatambp/modules/user/generated/mapper/mapping/UserMapper.xml
    # 2. 定制位置 - 配置方法2。同样需要配合pom.xml中build里面的配置。
    #- classpath*:/liuyang/testdatambp/modules/user/generated/mapper/mapping/UserMapper.xml
    # 实测这个配置可以搞定所有(Actor ok, User ok, ActorFilm ok)（推荐）
    - classpath*:**/*Mapper.xml
    #- classpath*:/**/mapping/*.xml